version: '2'
services:
  mongodb:
    image: mongo:3

  redis:
    image: redis:latest

  http:
    image: nginx:latest

  dynamodb:
    image: deangiberson/aws-dynamodb-local:latest

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb

  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
      DB_USER: me
      DB_PASS: secret
      DB_NAME: mydb

  memcached:
    image: memcached

  await:
    image: saltside/await
    build: .
